### PR TITLE
Oreo camera - update fixes from stock one. 

### PR DESCRIPTION
**Pull request by wiktorek140**
This partially fixes gcam modded. Still work sluggish because of hdr processing but didnt crash.

### CODE REVIEW

**Comment by JarlPenguin** [comment]
Does this break stock camera on HAL1? Aka snap

**Comment by wiktorek140** [comment]
Nope. Moto cam, los cam(snap) and gcam mod (little sluggish) work

**Comment by JarlPenguin** [comment]
@wiktorek140 everything?

**Comment by wiktorek140** [comment]
U can ingnore one about coresight

**Comment by JarlPenguin** [comment]
@wiktorek140 What does that mean

**Comment by wiktorek140** [comment]
Coresight is a debug solution introduced by qcom, it can be safely removed. It decrease boot time a little

**Comment by JarlPenguin** [comment]
@wiktorek140 Ok

**Pull request merged**
